# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "Services"
 url = "/#services"
 weight = 10

[[main]]
 name = "Blog"
 pageRef = "posts"
 weight = 20

# [[main]]
#  name = "About"
#  weight = 30

[[main]]
 name = "Contact"
 url = "/#contact"
 weight = 40


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Terms & Conditions"
  pageRef = "/terms-conditions"
  weight = 10

[[footer]]
  name = "Privacy"
  pageRef = "/privacy-policy"
  weight = 20

[[footer]]
  name = "Disclaimer"
  pageRef = "/disclaimer"
  weight = 20

[[footer]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/Roger_Noble"
  weight = 200

[[footer]]
 identifier = "linkedin"
 pre = "linkedin"
 weight = 300
 url = "https://www.linkedin.com/company/noble-dynamic"

[[footer]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/nobledynamic"
  weight = 400